// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.my.jni.dlib.data;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface LandmarkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.my.jni.dlib.data.Landmark)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 x = 1;</code>
     */
    int getX();

    /**
     * <code>uint32 y = 2;</code>
     */
    int getY();
  }
  /**
   * Protobuf type {@code com.my.jni.dlib.data.Landmark}
   */
  public  static final class Landmark extends
      com.google.protobuf.GeneratedMessageLite<
          Landmark, Landmark.Builder> implements
      // @@protoc_insertion_point(message_implements:com.my.jni.dlib.data.Landmark)
      LandmarkOrBuilder {
    private Landmark() {
    }
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>uint32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }
    /**
     * <code>uint32 x = 1;</code>
     */
    private void setX(int value) {
      
      x_ = value;
    }
    /**
     * <code>uint32 x = 1;</code>
     */
    private void clearX() {
      
      x_ = 0;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>uint32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }
    /**
     * <code>uint32 y = 2;</code>
     */
    private void setY(int value) {
      
      y_ = value;
    }
    /**
     * <code>uint32 y = 2;</code>
     */
    private void clearY() {
      
      y_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeUInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeUInt32(2, y_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, y_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.my.jni.dlib.data.Messages.Landmark parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.my.jni.dlib.data.Messages.Landmark parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.my.jni.dlib.data.Messages.Landmark parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.my.jni.dlib.data.Messages.Landmark parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.my.jni.dlib.data.Messages.Landmark parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.my.jni.dlib.data.Messages.Landmark parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.my.jni.dlib.data.Messages.Landmark parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.my.jni.dlib.data.Messages.Landmark parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.my.jni.dlib.data.Messages.Landmark parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.my.jni.dlib.data.Messages.Landmark parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.my.jni.dlib.data.Messages.Landmark prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.my.jni.dlib.data.Landmark}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.my.jni.dlib.data.Messages.Landmark, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.my.jni.dlib.data.Landmark)
        com.my.jni.dlib.data.Messages.LandmarkOrBuilder {
      // Construct using com.my.jni.dlib.data.Messages.Landmark.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 x = 1;</code>
       */
      public int getX() {
        return instance.getX();
      }
      /**
       * <code>uint32 x = 1;</code>
       */
      public Builder setX(int value) {
        copyOnWrite();
        instance.setX(value);
        return this;
      }
      /**
       * <code>uint32 x = 1;</code>
       */
      public Builder clearX() {
        copyOnWrite();
        instance.clearX();
        return this;
      }

      /**
       * <code>uint32 y = 2;</code>
       */
      public int getY() {
        return instance.getY();
      }
      /**
       * <code>uint32 y = 2;</code>
       */
      public Builder setY(int value) {
        copyOnWrite();
        instance.setY(value);
        return this;
      }
      /**
       * <code>uint32 y = 2;</code>
       */
      public Builder clearY() {
        copyOnWrite();
        instance.clearY();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.my.jni.dlib.data.Landmark)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.my.jni.dlib.data.Messages.Landmark();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.my.jni.dlib.data.Messages.Landmark other = (com.my.jni.dlib.data.Messages.Landmark) arg1;
          x_ = visitor.visitInt(x_ != 0, x_,
              other.x_ != 0, other.x_);
          y_ = visitor.visitInt(y_ != 0, y_,
              other.y_ != 0, other.y_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  x_ = input.readUInt32();
                  break;
                }
                case 16: {

                  y_ = input.readUInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.my.jni.dlib.data.Messages.Landmark.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.my.jni.dlib.data.Landmark)
    private static final com.my.jni.dlib.data.Messages.Landmark DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Landmark();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.my.jni.dlib.data.Messages.Landmark getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Landmark> PARSER;

    public static com.google.protobuf.Parser<Landmark> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface FaceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.my.jni.dlib.data.Face)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    java.util.List<com.my.jni.dlib.data.Messages.Landmark> 
        getLandmarksList();
    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    com.my.jni.dlib.data.Messages.Landmark getLandmarks(int index);
    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    int getLandmarksCount();
  }
  /**
   * Protobuf type {@code com.my.jni.dlib.data.Face}
   */
  public  static final class Face extends
      com.google.protobuf.GeneratedMessageLite<
          Face, Face.Builder> implements
      // @@protoc_insertion_point(message_implements:com.my.jni.dlib.data.Face)
      FaceOrBuilder {
    private Face() {
      landmarks_ = emptyProtobufList();
    }
    public static final int LANDMARKS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.my.jni.dlib.data.Messages.Landmark> landmarks_;
    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    public java.util.List<com.my.jni.dlib.data.Messages.Landmark> getLandmarksList() {
      return landmarks_;
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    public java.util.List<? extends com.my.jni.dlib.data.Messages.LandmarkOrBuilder> 
        getLandmarksOrBuilderList() {
      return landmarks_;
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    public int getLandmarksCount() {
      return landmarks_.size();
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    public com.my.jni.dlib.data.Messages.Landmark getLandmarks(int index) {
      return landmarks_.get(index);
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    public com.my.jni.dlib.data.Messages.LandmarkOrBuilder getLandmarksOrBuilder(
        int index) {
      return landmarks_.get(index);
    }
    private void ensureLandmarksIsMutable() {
      if (!landmarks_.isModifiable()) {
        landmarks_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(landmarks_);
       }
    }

    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    private void setLandmarks(
        int index, com.my.jni.dlib.data.Messages.Landmark value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureLandmarksIsMutable();
      landmarks_.set(index, value);
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    private void setLandmarks(
        int index, com.my.jni.dlib.data.Messages.Landmark.Builder builderForValue) {
      ensureLandmarksIsMutable();
      landmarks_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    private void addLandmarks(com.my.jni.dlib.data.Messages.Landmark value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureLandmarksIsMutable();
      landmarks_.add(value);
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    private void addLandmarks(
        int index, com.my.jni.dlib.data.Messages.Landmark value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureLandmarksIsMutable();
      landmarks_.add(index, value);
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    private void addLandmarks(
        com.my.jni.dlib.data.Messages.Landmark.Builder builderForValue) {
      ensureLandmarksIsMutable();
      landmarks_.add(builderForValue.build());
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    private void addLandmarks(
        int index, com.my.jni.dlib.data.Messages.Landmark.Builder builderForValue) {
      ensureLandmarksIsMutable();
      landmarks_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    private void addAllLandmarks(
        java.lang.Iterable<? extends com.my.jni.dlib.data.Messages.Landmark> values) {
      ensureLandmarksIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, landmarks_);
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    private void clearLandmarks() {
      landmarks_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
     */
    private void removeLandmarks(int index) {
      ensureLandmarksIsMutable();
      landmarks_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < landmarks_.size(); i++) {
        output.writeMessage(1, landmarks_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < landmarks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, landmarks_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.my.jni.dlib.data.Messages.Face parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.my.jni.dlib.data.Messages.Face parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.my.jni.dlib.data.Messages.Face parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.my.jni.dlib.data.Messages.Face parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.my.jni.dlib.data.Messages.Face parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.my.jni.dlib.data.Messages.Face parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.my.jni.dlib.data.Messages.Face parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.my.jni.dlib.data.Messages.Face parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.my.jni.dlib.data.Messages.Face parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.my.jni.dlib.data.Messages.Face parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.my.jni.dlib.data.Messages.Face prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.my.jni.dlib.data.Face}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.my.jni.dlib.data.Messages.Face, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.my.jni.dlib.data.Face)
        com.my.jni.dlib.data.Messages.FaceOrBuilder {
      // Construct using com.my.jni.dlib.data.Messages.Face.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
       */
      public java.util.List<com.my.jni.dlib.data.Messages.Landmark> getLandmarksList() {
        return java.util.Collections.unmodifiableList(
            instance.getLandmarksList());
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
       */
      public int getLandmarksCount() {
        return instance.getLandmarksCount();
      }/**
       * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
       */
      public com.my.jni.dlib.data.Messages.Landmark getLandmarks(int index) {
        return instance.getLandmarks(index);
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
       */
      public Builder setLandmarks(
          int index, com.my.jni.dlib.data.Messages.Landmark value) {
        copyOnWrite();
        instance.setLandmarks(index, value);
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
       */
      public Builder setLandmarks(
          int index, com.my.jni.dlib.data.Messages.Landmark.Builder builderForValue) {
        copyOnWrite();
        instance.setLandmarks(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
       */
      public Builder addLandmarks(com.my.jni.dlib.data.Messages.Landmark value) {
        copyOnWrite();
        instance.addLandmarks(value);
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
       */
      public Builder addLandmarks(
          int index, com.my.jni.dlib.data.Messages.Landmark value) {
        copyOnWrite();
        instance.addLandmarks(index, value);
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
       */
      public Builder addLandmarks(
          com.my.jni.dlib.data.Messages.Landmark.Builder builderForValue) {
        copyOnWrite();
        instance.addLandmarks(builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
       */
      public Builder addLandmarks(
          int index, com.my.jni.dlib.data.Messages.Landmark.Builder builderForValue) {
        copyOnWrite();
        instance.addLandmarks(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
       */
      public Builder addAllLandmarks(
          java.lang.Iterable<? extends com.my.jni.dlib.data.Messages.Landmark> values) {
        copyOnWrite();
        instance.addAllLandmarks(values);
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
       */
      public Builder clearLandmarks() {
        copyOnWrite();
        instance.clearLandmarks();
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Landmark landmarks = 1;</code>
       */
      public Builder removeLandmarks(int index) {
        copyOnWrite();
        instance.removeLandmarks(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.my.jni.dlib.data.Face)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.my.jni.dlib.data.Messages.Face();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          landmarks_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.my.jni.dlib.data.Messages.Face other = (com.my.jni.dlib.data.Messages.Face) arg1;
          landmarks_= visitor.visitList(landmarks_, other.landmarks_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!landmarks_.isModifiable()) {
                    landmarks_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(landmarks_);
                  }
                  landmarks_.add(
                      input.readMessage(com.my.jni.dlib.data.Messages.Landmark.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.my.jni.dlib.data.Messages.Face.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.my.jni.dlib.data.Face)
    private static final com.my.jni.dlib.data.Messages.Face DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Face();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.my.jni.dlib.data.Messages.Face getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Face> PARSER;

    public static com.google.protobuf.Parser<Face> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface FaceListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.my.jni.dlib.data.FaceList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    java.util.List<com.my.jni.dlib.data.Messages.Face> 
        getFacesList();
    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    com.my.jni.dlib.data.Messages.Face getFaces(int index);
    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    int getFacesCount();
  }
  /**
   * Protobuf type {@code com.my.jni.dlib.data.FaceList}
   */
  public  static final class FaceList extends
      com.google.protobuf.GeneratedMessageLite<
          FaceList, FaceList.Builder> implements
      // @@protoc_insertion_point(message_implements:com.my.jni.dlib.data.FaceList)
      FaceListOrBuilder {
    private FaceList() {
      faces_ = emptyProtobufList();
    }
    public static final int FACES_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.my.jni.dlib.data.Messages.Face> faces_;
    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    public java.util.List<com.my.jni.dlib.data.Messages.Face> getFacesList() {
      return faces_;
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    public java.util.List<? extends com.my.jni.dlib.data.Messages.FaceOrBuilder> 
        getFacesOrBuilderList() {
      return faces_;
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    public int getFacesCount() {
      return faces_.size();
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    public com.my.jni.dlib.data.Messages.Face getFaces(int index) {
      return faces_.get(index);
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    public com.my.jni.dlib.data.Messages.FaceOrBuilder getFacesOrBuilder(
        int index) {
      return faces_.get(index);
    }
    private void ensureFacesIsMutable() {
      if (!faces_.isModifiable()) {
        faces_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(faces_);
       }
    }

    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    private void setFaces(
        int index, com.my.jni.dlib.data.Messages.Face value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureFacesIsMutable();
      faces_.set(index, value);
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    private void setFaces(
        int index, com.my.jni.dlib.data.Messages.Face.Builder builderForValue) {
      ensureFacesIsMutable();
      faces_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    private void addFaces(com.my.jni.dlib.data.Messages.Face value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureFacesIsMutable();
      faces_.add(value);
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    private void addFaces(
        int index, com.my.jni.dlib.data.Messages.Face value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureFacesIsMutable();
      faces_.add(index, value);
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    private void addFaces(
        com.my.jni.dlib.data.Messages.Face.Builder builderForValue) {
      ensureFacesIsMutable();
      faces_.add(builderForValue.build());
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    private void addFaces(
        int index, com.my.jni.dlib.data.Messages.Face.Builder builderForValue) {
      ensureFacesIsMutable();
      faces_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    private void addAllFaces(
        java.lang.Iterable<? extends com.my.jni.dlib.data.Messages.Face> values) {
      ensureFacesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, faces_);
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    private void clearFaces() {
      faces_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
     */
    private void removeFaces(int index) {
      ensureFacesIsMutable();
      faces_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < faces_.size(); i++) {
        output.writeMessage(1, faces_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < faces_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, faces_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.my.jni.dlib.data.Messages.FaceList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.my.jni.dlib.data.Messages.FaceList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.my.jni.dlib.data.Messages.FaceList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.my.jni.dlib.data.Messages.FaceList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.my.jni.dlib.data.Messages.FaceList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.my.jni.dlib.data.Messages.FaceList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.my.jni.dlib.data.Messages.FaceList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.my.jni.dlib.data.Messages.FaceList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.my.jni.dlib.data.Messages.FaceList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.my.jni.dlib.data.Messages.FaceList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.my.jni.dlib.data.Messages.FaceList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.my.jni.dlib.data.FaceList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.my.jni.dlib.data.Messages.FaceList, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.my.jni.dlib.data.FaceList)
        com.my.jni.dlib.data.Messages.FaceListOrBuilder {
      // Construct using com.my.jni.dlib.data.Messages.FaceList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
       */
      public java.util.List<com.my.jni.dlib.data.Messages.Face> getFacesList() {
        return java.util.Collections.unmodifiableList(
            instance.getFacesList());
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
       */
      public int getFacesCount() {
        return instance.getFacesCount();
      }/**
       * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
       */
      public com.my.jni.dlib.data.Messages.Face getFaces(int index) {
        return instance.getFaces(index);
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
       */
      public Builder setFaces(
          int index, com.my.jni.dlib.data.Messages.Face value) {
        copyOnWrite();
        instance.setFaces(index, value);
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
       */
      public Builder setFaces(
          int index, com.my.jni.dlib.data.Messages.Face.Builder builderForValue) {
        copyOnWrite();
        instance.setFaces(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
       */
      public Builder addFaces(com.my.jni.dlib.data.Messages.Face value) {
        copyOnWrite();
        instance.addFaces(value);
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
       */
      public Builder addFaces(
          int index, com.my.jni.dlib.data.Messages.Face value) {
        copyOnWrite();
        instance.addFaces(index, value);
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
       */
      public Builder addFaces(
          com.my.jni.dlib.data.Messages.Face.Builder builderForValue) {
        copyOnWrite();
        instance.addFaces(builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
       */
      public Builder addFaces(
          int index, com.my.jni.dlib.data.Messages.Face.Builder builderForValue) {
        copyOnWrite();
        instance.addFaces(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
       */
      public Builder addAllFaces(
          java.lang.Iterable<? extends com.my.jni.dlib.data.Messages.Face> values) {
        copyOnWrite();
        instance.addAllFaces(values);
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
       */
      public Builder clearFaces() {
        copyOnWrite();
        instance.clearFaces();
        return this;
      }
      /**
       * <code>repeated .com.my.jni.dlib.data.Face faces = 1;</code>
       */
      public Builder removeFaces(int index) {
        copyOnWrite();
        instance.removeFaces(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.my.jni.dlib.data.FaceList)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.my.jni.dlib.data.Messages.FaceList();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          faces_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.my.jni.dlib.data.Messages.FaceList other = (com.my.jni.dlib.data.Messages.FaceList) arg1;
          faces_= visitor.visitList(faces_, other.faces_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!faces_.isModifiable()) {
                    faces_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(faces_);
                  }
                  faces_.add(
                      input.readMessage(com.my.jni.dlib.data.Messages.Face.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.my.jni.dlib.data.Messages.FaceList.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.my.jni.dlib.data.FaceList)
    private static final com.my.jni.dlib.data.Messages.FaceList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FaceList();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.my.jni.dlib.data.Messages.FaceList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FaceList> PARSER;

    public static com.google.protobuf.Parser<FaceList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
