// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/ProtoGrid.proto

package com.my.algorithm.proto;

public final class ProtoGrid {
  private ProtoGrid() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MsgGridOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.my.algorithm.proto.MsgGrid)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    java.util.List<com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot> 
        getSlotsList();
    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot getSlots(int index);
    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    int getSlotsCount();
  }
  /**
   * Protobuf type {@code com.my.algorithm.proto.MsgGrid}
   */
  public  static final class MsgGrid extends
      com.google.protobuf.GeneratedMessageLite<
          MsgGrid, MsgGrid.Builder> implements
      // @@protoc_insertion_point(message_implements:com.my.algorithm.proto.MsgGrid)
      MsgGridOrBuilder {
    private MsgGrid() {
      name_ = "";
      slots_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required uint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>required uint64 id = 1;</code>
     */
    private void setId(long value) {
      bitField0_ |= 0x00000001;
      id_ = value;
    }
    /**
     * <code>required uint64 id = 1;</code>
     */
    private void clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.String name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>required string name = 2;</code>
     */
    private void setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
    }
    /**
     * <code>required string name = 2;</code>
     */
    private void clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>required string name = 2;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value.toStringUtf8();
    }

    public static final int SLOTS_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot> slots_;
    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    public java.util.List<com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot> getSlotsList() {
      return slots_;
    }
    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    public java.util.List<? extends com.my.algorithm.proto.ProtoRectSlot.MsgRectSlotOrBuilder> 
        getSlotsOrBuilderList() {
      return slots_;
    }
    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    public int getSlotsCount() {
      return slots_.size();
    }
    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    public com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot getSlots(int index) {
      return slots_.get(index);
    }
    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    public com.my.algorithm.proto.ProtoRectSlot.MsgRectSlotOrBuilder getSlotsOrBuilder(
        int index) {
      return slots_.get(index);
    }
    private void ensureSlotsIsMutable() {
      if (!slots_.isModifiable()) {
        slots_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(slots_);
       }
    }

    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    private void setSlots(
        int index, com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureSlotsIsMutable();
      slots_.set(index, value);
    }
    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    private void setSlots(
        int index, com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot.Builder builderForValue) {
      ensureSlotsIsMutable();
      slots_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    private void addSlots(com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureSlotsIsMutable();
      slots_.add(value);
    }
    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    private void addSlots(
        int index, com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureSlotsIsMutable();
      slots_.add(index, value);
    }
    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    private void addSlots(
        com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot.Builder builderForValue) {
      ensureSlotsIsMutable();
      slots_.add(builderForValue.build());
    }
    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    private void addSlots(
        int index, com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot.Builder builderForValue) {
      ensureSlotsIsMutable();
      slots_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    private void addAllSlots(
        java.lang.Iterable<? extends com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot> values) {
      ensureSlotsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, slots_);
    }
    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    private void clearSlots() {
      slots_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
     */
    private void removeSlots(int index) {
      ensureSlotsIsMutable();
      slots_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(2, getName());
      }
      for (int i = 0; i < slots_.size(); i++) {
        output.writeMessage(3, slots_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      for (int i = 0; i < slots_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, slots_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.my.algorithm.proto.ProtoGrid.MsgGrid parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.my.algorithm.proto.ProtoGrid.MsgGrid parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.my.algorithm.proto.ProtoGrid.MsgGrid parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.my.algorithm.proto.ProtoGrid.MsgGrid parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.my.algorithm.proto.ProtoGrid.MsgGrid parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.my.algorithm.proto.ProtoGrid.MsgGrid parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.my.algorithm.proto.ProtoGrid.MsgGrid parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.my.algorithm.proto.ProtoGrid.MsgGrid parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.my.algorithm.proto.ProtoGrid.MsgGrid parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.my.algorithm.proto.ProtoGrid.MsgGrid parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.my.algorithm.proto.ProtoGrid.MsgGrid prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.my.algorithm.proto.MsgGrid}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.my.algorithm.proto.ProtoGrid.MsgGrid, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.my.algorithm.proto.MsgGrid)
        com.my.algorithm.proto.ProtoGrid.MsgGridOrBuilder {
      // Construct using com.my.algorithm.proto.ProtoGrid.MsgGrid.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required uint64 id = 1;</code>
       */
      public boolean hasId() {
        return instance.hasId();
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public long getId() {
        return instance.getId();
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return instance.hasName();
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
       */
      public java.util.List<com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot> getSlotsList() {
        return java.util.Collections.unmodifiableList(
            instance.getSlotsList());
      }
      /**
       * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
       */
      public int getSlotsCount() {
        return instance.getSlotsCount();
      }/**
       * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
       */
      public com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot getSlots(int index) {
        return instance.getSlots(index);
      }
      /**
       * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
       */
      public Builder setSlots(
          int index, com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot value) {
        copyOnWrite();
        instance.setSlots(index, value);
        return this;
      }
      /**
       * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
       */
      public Builder setSlots(
          int index, com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot.Builder builderForValue) {
        copyOnWrite();
        instance.setSlots(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
       */
      public Builder addSlots(com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot value) {
        copyOnWrite();
        instance.addSlots(value);
        return this;
      }
      /**
       * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
       */
      public Builder addSlots(
          int index, com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot value) {
        copyOnWrite();
        instance.addSlots(index, value);
        return this;
      }
      /**
       * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
       */
      public Builder addSlots(
          com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot.Builder builderForValue) {
        copyOnWrite();
        instance.addSlots(builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
       */
      public Builder addSlots(
          int index, com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot.Builder builderForValue) {
        copyOnWrite();
        instance.addSlots(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
       */
      public Builder addAllSlots(
          java.lang.Iterable<? extends com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot> values) {
        copyOnWrite();
        instance.addAllSlots(values);
        return this;
      }
      /**
       * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
       */
      public Builder clearSlots() {
        copyOnWrite();
        instance.clearSlots();
        return this;
      }
      /**
       * <code>repeated .com.my.algorithm.proto.MsgRectSlot slots = 3;</code>
       */
      public Builder removeSlots(int index) {
        copyOnWrite();
        instance.removeSlots(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.my.algorithm.proto.MsgGrid)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.my.algorithm.proto.ProtoGrid.MsgGrid();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasId()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasName()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          for (int i = 0; i < getSlotsCount(); i++) {
            if (!getSlots(i).isInitialized()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          slots_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.my.algorithm.proto.ProtoGrid.MsgGrid other = (com.my.algorithm.proto.ProtoGrid.MsgGrid) arg1;
          id_ = visitor.visitLong(
              hasId(), id_,
              other.hasId(), other.id_);
          name_ = visitor.visitString(
              hasName(), name_,
              other.hasName(), other.name_);
          slots_= visitor.visitList(slots_, other.slots_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  id_ = input.readUInt64();
                  break;
                }
                case 18: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  name_ = s;
                  break;
                }
                case 26: {
                  if (!slots_.isModifiable()) {
                    slots_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(slots_);
                  }
                  slots_.add(
                      input.readMessage(com.my.algorithm.proto.ProtoRectSlot.MsgRectSlot.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.my.algorithm.proto.ProtoGrid.MsgGrid.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.my.algorithm.proto.MsgGrid)
    private static final com.my.algorithm.proto.ProtoGrid.MsgGrid DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgGrid();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.my.algorithm.proto.ProtoGrid.MsgGrid getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MsgGrid> PARSER;

    public static com.google.protobuf.Parser<MsgGrid> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
