// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/ProtoPhoto.proto

package com.my.algorithm.proto;

public final class ProtoPhoto {
  private ProtoPhoto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MsgPhotoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.my.algorithm.proto.MsgPhoto)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required float width = 2;</code>
     */
    boolean hasWidth();
    /**
     * <code>required float width = 2;</code>
     */
    float getWidth();

    /**
     * <code>required float height = 3;</code>
     */
    boolean hasHeight();
    /**
     * <code>required float height = 3;</code>
     */
    float getHeight();
  }
  /**
   * Protobuf type {@code com.my.algorithm.proto.MsgPhoto}
   */
  public  static final class MsgPhoto extends
      com.google.protobuf.GeneratedMessageLite<
          MsgPhoto, MsgPhoto.Builder> implements
      // @@protoc_insertion_point(message_implements:com.my.algorithm.proto.MsgPhoto)
      MsgPhotoOrBuilder {
    private MsgPhoto() {
    }
    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required uint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>required uint64 id = 1;</code>
     */
    private void setId(long value) {
      bitField0_ |= 0x00000001;
      id_ = value;
    }
    /**
     * <code>required uint64 id = 1;</code>
     */
    private void clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
    }

    public static final int WIDTH_FIELD_NUMBER = 2;
    private float width_;
    /**
     * <code>required float width = 2;</code>
     */
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float width = 2;</code>
     */
    public float getWidth() {
      return width_;
    }
    /**
     * <code>required float width = 2;</code>
     */
    private void setWidth(float value) {
      bitField0_ |= 0x00000002;
      width_ = value;
    }
    /**
     * <code>required float width = 2;</code>
     */
    private void clearWidth() {
      bitField0_ = (bitField0_ & ~0x00000002);
      width_ = 0F;
    }

    public static final int HEIGHT_FIELD_NUMBER = 3;
    private float height_;
    /**
     * <code>required float height = 3;</code>
     */
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float height = 3;</code>
     */
    public float getHeight() {
      return height_;
    }
    /**
     * <code>required float height = 3;</code>
     */
    private void setHeight(float value) {
      bitField0_ |= 0x00000004;
      height_ = value;
    }
    /**
     * <code>required float height = 3;</code>
     */
    private void clearHeight() {
      bitField0_ = (bitField0_ & ~0x00000004);
      height_ = 0F;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, width_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, height_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, width_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, height_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.my.algorithm.proto.ProtoPhoto.MsgPhoto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.my.algorithm.proto.ProtoPhoto.MsgPhoto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.my.algorithm.proto.ProtoPhoto.MsgPhoto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.my.algorithm.proto.ProtoPhoto.MsgPhoto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.my.algorithm.proto.ProtoPhoto.MsgPhoto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.my.algorithm.proto.ProtoPhoto.MsgPhoto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.my.algorithm.proto.ProtoPhoto.MsgPhoto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.my.algorithm.proto.ProtoPhoto.MsgPhoto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.my.algorithm.proto.ProtoPhoto.MsgPhoto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.my.algorithm.proto.ProtoPhoto.MsgPhoto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.my.algorithm.proto.ProtoPhoto.MsgPhoto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.my.algorithm.proto.MsgPhoto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.my.algorithm.proto.ProtoPhoto.MsgPhoto, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.my.algorithm.proto.MsgPhoto)
        com.my.algorithm.proto.ProtoPhoto.MsgPhotoOrBuilder {
      // Construct using com.my.algorithm.proto.ProtoPhoto.MsgPhoto.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required uint64 id = 1;</code>
       */
      public boolean hasId() {
        return instance.hasId();
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public long getId() {
        return instance.getId();
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>required float width = 2;</code>
       */
      public boolean hasWidth() {
        return instance.hasWidth();
      }
      /**
       * <code>required float width = 2;</code>
       */
      public float getWidth() {
        return instance.getWidth();
      }
      /**
       * <code>required float width = 2;</code>
       */
      public Builder setWidth(float value) {
        copyOnWrite();
        instance.setWidth(value);
        return this;
      }
      /**
       * <code>required float width = 2;</code>
       */
      public Builder clearWidth() {
        copyOnWrite();
        instance.clearWidth();
        return this;
      }

      /**
       * <code>required float height = 3;</code>
       */
      public boolean hasHeight() {
        return instance.hasHeight();
      }
      /**
       * <code>required float height = 3;</code>
       */
      public float getHeight() {
        return instance.getHeight();
      }
      /**
       * <code>required float height = 3;</code>
       */
      public Builder setHeight(float value) {
        copyOnWrite();
        instance.setHeight(value);
        return this;
      }
      /**
       * <code>required float height = 3;</code>
       */
      public Builder clearHeight() {
        copyOnWrite();
        instance.clearHeight();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.my.algorithm.proto.MsgPhoto)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.my.algorithm.proto.ProtoPhoto.MsgPhoto();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasId()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasWidth()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasHeight()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.my.algorithm.proto.ProtoPhoto.MsgPhoto other = (com.my.algorithm.proto.ProtoPhoto.MsgPhoto) arg1;
          id_ = visitor.visitLong(
              hasId(), id_,
              other.hasId(), other.id_);
          width_ = visitor.visitFloat(
              hasWidth(), width_,
              other.hasWidth(), other.width_);
          height_ = visitor.visitFloat(
              hasHeight(), height_,
              other.hasHeight(), other.height_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  id_ = input.readUInt64();
                  break;
                }
                case 21: {
                  bitField0_ |= 0x00000002;
                  width_ = input.readFloat();
                  break;
                }
                case 29: {
                  bitField0_ |= 0x00000004;
                  height_ = input.readFloat();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.my.algorithm.proto.ProtoPhoto.MsgPhoto.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.my.algorithm.proto.MsgPhoto)
    private static final com.my.algorithm.proto.ProtoPhoto.MsgPhoto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgPhoto();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.my.algorithm.proto.ProtoPhoto.MsgPhoto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MsgPhoto> PARSER;

    public static com.google.protobuf.Parser<MsgPhoto> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
